# Generated by Django 4.1.5 on 2023-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product-images')),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
