# Generated by Django 4.1.5 on 2023-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='title',
            field=models.CharField(default='Mobile', max_length=50),
        ),
    ]
