# Generated by Django 4.1.5 on 2023-03-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_detail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='desc',
            field=models.TextField(max_length=250),
        ),
    ]
